### ISSUE TITLE
Status & (M)ELPA?

### ISSUE THREAD

**Issue by Ambrevar** [tmalsburg/helm-org-contacts#1]
What's the status of this package?  Is it superseded by anything?

What about adding it to (M)ELPA?
And moving to the Helm organization?

**Comment by tmalsburg** [comment]
If there is sufficient interest, we could move it to Helm and MELPA.  The package is to my knowledge not superseded by another, but I may be wrong. I'm using this package on a daily basis and it suits my own needs reasonably well.  However, note that the org-contacts format that is assumed here is perhaps a bit non-standard / augmented.  I'm using the format generated by [this script](https://gist.github.com/tmalsburg/9747104) which tries to preserve as much info from the original Vcard file as possible.

**Comment by Ambrevar** [comment]
I've just tried it and it's great!

Considering both Helm and Org have a big user base, I think it would not be unreasonable to advertize it more :)

**Comment by Ambrevar** [comment]
Wait, I just noticed there is a significant overlap with `helm-mu-contacts`.  What do you think?

**Comment by tmalsburg** [comment]
helm-mu-contacts only shows emails extracted from your mailbox. It's not a general contacts manager and it shows you a lot of junk for large mailboxes.  I use both, helm-mu-contacts and helm-org-contacts, in conjunction via:

``` elisp
;; Combine mu contacts with org contacts:
(defun helm-org-contacts ()
  (interactive)
  (helm :sources '(helm-source-org-contacts helm-source-mu-contacts)
        :full-frame t
        :candidate-number-limit 500))
```

This way I get clean contact data from my address book and I can fall back to email addresses extracted from my mailbox if the person in question is missing in my address book.

**Comment by Ambrevar** [comment]
Excellent!

**Comment by Ambrevar** [comment]
You should add this example to the documentation ;)

**Comment by tmalsburg** [comment]
Good point, will do.

**Comment by tmalsburg** [comment]
Added a section on helm-mu-contacts to [the main page](https://github.com/tmalsburg/helm-org-contacts/blob/master/README.org#combination-with-helm-mu-contacts).

**Comment by Ambrevar** [comment]
I've packaged it for [Guix](https://www.gnu.org/software/guix/).

**Comment by tmalsburg** [comment]
Cool, thanks.  Haven't used Guix yet, but will look into it.

**Comment by tmalsburg** [comment]
It's easy these days to install straight (pun intended) from GitHub. So I'll close this issue for now.

``` elisp
(straight-use-package
 '(helm-org-contacts :type git :host github :repo "tmalsburg/helm-org-contacts"))
```
