### ISSUE TITLE
Why is it a multiline source?

### ISSUE THREAD

**Issue by Ambrevar** [tmalsburg/helm-org-contacts#3]
I've just realized that `helm-source-org-contacts` is a multiline source.  But all entries, in my case, fit on a single line.

Is there a case where entries could fit on multiple lines?  Or should we disable the multiline option?

**Comment by Ambrevar** [comment]
OK, I've just figured it out! :)  It's for when there are several `:EMAIL:` properties for instance.

That said, is it the right approach?

- With Org, `C-c C-x p` (`org-set-property`) will only see and set the first field.
- With mu4e, tab-completion on the "To:" field will only see the first field.  mu4e expects multiple addressees to be on the same line, e.g.

```org
* John Doe
:PROPERTIES:
:EMAIL: john@doe.org, john@doe.net
:END:
```
`helm-org-contacts-insert-plain-email` and `helm-org-contacts-insert-email-with-name` don't work properly with the above structure.

**Comment by tmalsburg** [comment]
Please have a look at the screenshot and example on the [startpage](https://github.com/tmalsburg/helm-org-contacts) of this repository.  If someone has multiple e-mail addresses, you need multiple entries one for each.  E.g.:

```
* Robert Moskowitz
  :PROPERTIES:
  :EMAIL: rgm-ietf@htt-consult.com (WORK, INTERNET)
  :EMAIL: rgm-ietf@gmail.com (HOME, INTERNET)
  :N: Moskowitz;Robert;;;
  :END:
```

**Comment by Ambrevar** [comment]
As I said in my previous comment, this does not work with tab-completion on the "To:" field in mu4e.  It expects comma-separated email addresses.

**Comment by tmalsburg** [comment]
Ah sorry, missed the bit about mu4e.  It would be good to update the code for address completion in mu4e so that it works with multiple EMAIL fields.  Shouldn't be difficult.  Not sure, though, where the responsible code lives.  I had a quick look at the mu4e sources but couldn't find it.

**Comment by tmalsburg** [comment]
Re multiline: I think it's useful and I'd like to keep it.  The majority of entries in my address book need multiple lines for display.

**Comment by Ambrevar** [comment]
@djcb?

**Comment by djcb** [comment]
mu4e doesn't do anything special for `org-contacts`,  so if there's only completion on the first of multiple contacts, it's probably something to do with how org-contacts handle the emacs completion mechs.

**Comment by Ambrevar** [comment]
You are right, the completion is done in one of the functions bound to `org-contacts-complete-functions`.
It seems that they only get the first EMAIL property.
I'm not sure org-contacts is maintained anymore, but it's part of org-contrib, so I'll see if I can get a patch pushed there.  Let me know if you know better.

**Comment by tmalsburg** [comment]
I received my `org-contacts.el` via Elpa as part of package `org-plus-contrib`.  The package references orgmode.org as the source.  So, yes, it seems that org-contrib is  the place to submit the patch.

**Comment by tmalsburg** [comment]
I'm closing this issue.  But feel free to reopen if necessary.
