### ISSUE TITLE
org-templates help

### ISSUE THREAD

**Issue by OrionRandD** [tmalsburg/helm-org-contacts#4]
How can I join these two templates, so that the first one becomes only an option in the templates list?

1. -------------------------------------------------------

(use-package org
:ensure org-plus-contrib)

(use-package org-contacts
  :ensure nil
  :after org)

(use-package org-capture
:ensure nil
:after org
:preface
(defvar my/org-contacts-template "* %(org-contacts-template-name)
:PROPERTIES:
:ALIAS: %^{hefis}
:NICKNAME: %^{hefistion}
:PHONE: %^{123-456-789}
:PHONE: %^{123-456-789}
:EMAIL: %(org-contacts-template-email)
:EMAIL: %(org-contacts-template-email)
:ADDRESS: %^{289 Cleveland St. Brooklyn, 11206 NY, USA}
:BIRTHDAY: %^{dd-mm-yyyy}
:NOTE: %^{NOTE}
:END:" "Template for org-contacts.")
:custom
(org-capture-templates
`(("c" "Contact" entry (file+headline "/org/Gtd_mylife/org-capture_tpls/my-contacts.org" "Friends"),
my/org-contacts-template
:empty-lines 1))))

2. -------------------------------------------------

(define-key global-map "\C-cc" 'org-capture)

(setq org-capture-templates
'(("a" "Appointment" entry
(file+headline
(concat org-directory "~/Gtd_mylife/org-capture_tpls/my-appointments.org")
"Calendar")
"* APPT %^{Description} %^g\n%?\nAdded: %U")

 ("m" "Brain" entry (function org-brain-goto-end)
    "* %i%?" :empty-lines 1)

;; for todo tasks

("d" "Long Tail TODO Task" entry
(file+headline "" "Tasks")
"* TODO %?\n %u\n %a")

;; for tasks

("t" "Task Diary" entry
(file+datetree
(concat org-directory "~/Gtd_mylife/org-capture_tpls/taskdiary.org"))
"* TODO %^{Description} %^g\n%?\nAdded: %U")

;; for long tail tasks

("d" "Long Tail TODO Task" entry
(file+headline "" "Tasks")
"* TODO %?\n %u\n %a")

;; for general notes

("n" "Notes" entry
(file+datetree
(concat org-directory "~/Gtd_mylife/org-capture_tpls/my-notes.org"))

  "* %^{Description} %^g %?\nAdded: %U")

;; for dreams

("i" "Dreams" entry
(file+datetree
(concat org-directory "~/Gtd_mylife/org-capture_tpls/my-dreams.org"))

"* %^{Description} %^g %?\nAdded: %U")

;; for journalling

 ("j" "Journal" entry
  (file+datetree
   (concat org-directory "~/Gtd_mylife/org-capture_tpls/my-journal.org"))
  "** %^{Heading}")

;; for hugo blogging

   ("o" "Posts"
 (file+datetree (concat org-directory "~/blog/content/posts/my-post.org")

"* TODO %^{Description} %^g\n%?\nAdded: %U"))

;; for capturing books to read

   ("b" "Book" entry (file+headline "~/Gtd_mylife/org-capture_tpls/books-to_read.org" "books to read")
  "* TODO %\\1 - %\\2%?\n%U\n:PROPERTIES:\n:NAME: %^{NAME}\n:TITLE: %^{TITLE}\n:END:\n")

;; for log time

   ("l" "Log Time" entry
  (file+datetree
   (concat org-directory "~/Gtd_mylife/org-capture_tpls/timelog.org"))
  "** %U - %^{Activity}  :TIME:")

;; for capturing chunks of webpages and/or webpages themselves with W3m or EWW

   ("w" "Website" plain 
  (function org-website-clipper)
  "* %a\n%T\n" :immediate-finish t)))
-------------------------------------------

**Comment by tmalsburg** [comment]
I'm not sure what you're asking and I'm not familiar with `use-package`.  Could you please verbally explain what you want to achieve?
