### ISSUE TITLE
wrong-type-argument

### ISSUE THREAD

**Issue by novoid** [tmalsburg/helm-org-contacts#6]
Hi,
I just checked out this Git repo and tested it with my setup:

- GNU Emacs 26.3 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.11) of 2019-09-23, modified by Debian
- helm-20200128.1831
- dash-20200119.2310
- s-20180406.808

Setup:
```
(use-package helm-org-contacts
   :load-path  (lambda () (expand-file-name (concat my-user-emacs-directory "contrib/helm-org-contacts/")))
   :after org
)
```

When invoking `helm-org-contacts`, I get:
```
custom-initialize-reset: In ‘Contacts’ source: ‘helm-org-contacts-get-contacts’ 
 (wrong-type-argument listp "~/org/contacts.org")
```

I've checked the variable: `org-contacts-files’s value is "~/org/contacts.org"` which seems fine to me. When I set it to the absolute path to my `contacts.org`, the result is the same.

What is going on here?

**Comment by novoid** [comment]
I found out, what the issue was.
My `org-contacts-files` should have been a list of strings. Instead, it was a string.

**Comment by tmalsburg** [comment]
Glad you could fix it. :)
